import IndustryLandingPage, { type LandingContent } from '@/components/landing/IndustryLandingPage'

type PriorityLocalKey = 'doctorsJaipur' | 'jewelleryJaipur' | 'realEstateJaipur'

const SHARED_PROOF = [
  { emoji: '💰', value: '₹10Cr+', label: 'Ad spend managed' },
  { emoji: '🚀', value: '10,000+', label: 'Campaigns delivered' },
  { emoji: '📍', value: 'Jaipur', label: 'Growth Escalators HQ' },
]

export const PRIORITY_LOCAL_PAGES: Record<PriorityLocalKey, LandingContent> = {
  doctorsJaipur: {
    industryLabel: 'Jaipur Healthcare',
    hero: {
      badge: 'JAIPUR HEALTHCARE · LOCAL SEO · GOOGLE ADS · PATIENT ACQUISITION',
      headlineLines: ['Marketing Agency for', 'Doctors in Jaipur'],
      cyclingWords: ['Win high-intent local searches.', 'Turn enquiries into appointments.', 'Build doctor authority.', 'Track booked patients, not clicks.'],
      subhead: 'Growth Escalators helps doctors, clinics and hospitals in Jaipur build measurable patient-acquisition systems across Google Search, Google Maps, Meta, landing pages and follow-up. The goal is not more random leads — it is more qualified appointment demand for the services you actually want to grow.',
      primaryCta: { label: 'Book a Free Clinic Audit', href: '#lead-form' },
      secondaryCta: { label: 'See Healthcare Proof ↓', href: '#results' },
      statPills: SHARED_PROOF,
      image: { src: '/industries/healthcare/4.jpg', alt: 'Doctor consulting at a healthcare clinic in Jaipur' },
    },
    painPointsTag: 'WHERE PATIENT GROWTH BREAKS',
    painPointsHeadline: 'Most clinics do not have a traffic problem — they have a patient journey problem',
    painPoints: [
      { emoji: '📍', title: 'Your strongest treatments are hard to find locally', body: 'A clinic can have an excellent doctor and still lose high-intent searches because its Google Business Profile, treatment pages, reviews and location signals are weaker than competing practices.' },
      { emoji: '📞', title: 'Enquiries arrive but are not converted consistently', body: 'Slow response, unclear qualification and weak follow-up turn paid enquiries into missed appointments. Marketing and front-desk process have to be measured together.' },
      { emoji: '🩺', title: 'Every speciality is marketed like a generic clinic', body: 'A joint-replacement patient, an IVF couple and a dermatology patient make decisions differently. Search intent, trust proof and landing-page information should reflect the speciality.' },
      { emoji: '⚖️', title: 'Healthcare claims create avoidable ad risk', body: 'Sensitive health advertising needs conservative claims, careful targeting and truthful patient communication. We build around platform policy rather than trying to outsmart it.' },
    ],
    aiAdvantage: {
      tag: 'SEO + AI SEARCH READINESS',
      headline: 'Make the clinic understandable to Google, Maps and answer engines',
      subhead: 'Strong healthcare visibility starts with clear entity information, treatment-level pages and direct answers to the questions patients ask before choosing a doctor.',
      cards: [
        { emoji: '🧭', title: 'Speciality-level search architecture', body: 'We map services and treatments to distinct search intent instead of forcing every query onto one generic clinic page.' },
        { emoji: '📚', title: 'Answer-first medical content', body: 'Pages answer practical patient questions clearly while avoiding unsupported cure claims or guarantees.' },
        { emoji: '⭐', title: 'Local trust signals', body: 'Google Business Profile accuracy, reviews, doctor credentials and location consistency support both discovery and patient confidence.' },
        { emoji: '📊', title: 'Appointment-level measurement', body: 'Where the clinic can provide the data, we connect campaigns to booked appointments and lead quality so optimisation is based on outcomes.' },
      ],
    },
    servicesTag: 'THE PATIENT ACQUISITION STACK',
    servicesHeadline: 'A focused growth system for Jaipur doctors and clinics',
    servicesSubhead: 'Local visibility, paid demand, conversion and follow-up work as one system.',
    services: [
      { title: 'Google Maps & Local SEO', body: 'Google Business Profile optimisation, location consistency, review strategy, local landing pages and treatment-level search coverage for Jaipur intent.' },
      { title: 'Google Search Ads', body: 'Capture patients already searching for a doctor, treatment or second opinion, with campaigns structured around the services the clinic wants to grow.' },
      { title: 'Meta Patient Education Campaigns', body: 'Educational creative and consultation-led campaigns where Meta is appropriate, built around conservative healthcare messaging and clear next steps.' },
      { title: 'Clinic Landing Pages & CRO', body: 'Mobile-first treatment and doctor pages with credentials, FAQs, trust signals and appointment actions placed where patients need them.' },
      { title: 'WhatsApp & Lead Follow-up', body: 'Fast acknowledgement, qualification and reminder flows so qualified enquiries are less likely to disappear between form submission and appointment.' },
      { title: 'Measurement & Lead Quality', body: 'Campaign reporting organised around source, speciality, appointment status and lead quality where clinic operations allow those outcomes to be captured.' },
    ],
    resultsTag: 'VERIFIED HEALTHCARE PROOF',
    resultsHeadline: 'A real healthcare result already in our evidence set',
    resultHighlight: {
      label: 'MULTISPECIALTY CLINIC · GOOGLE ADS + LOCAL SEO',
      name: 'Rohit Sharma',
      detail: 'Healthcare Clinic Owner',
      quote: 'Running a multispecialty clinic, I had no idea how to get patients digitally. Growth Escalators set up Google Ads and a local SEO strategy. Within 4 months, online appointment bookings were up 220%.',
      metrics: [
        { value: '+220%', label: 'Online appointment bookings' },
        { value: '4 months', label: 'Reported period' },
      ],
    },
    processTag: 'OUR SIX-SIGMA-INSPIRED GROWTH LOOP',
    processHeadline: 'Measure the patient journey before adding more spend',
    process: [
      { step: '01', title: 'Measure', body: 'Audit search visibility, ads, treatment pages, response time, appointment flow and the information currently available about lead quality.' },
      { step: '02', title: 'Diagnose', body: 'Identify the single highest-impact constraint: visibility, lead quality, conversion, follow-up, reviews or page trust.' },
      { step: '03', title: 'Improve', body: 'Fix the constraint with the smallest set of changes capable of moving appointment outcomes.' },
      { step: '04', title: 'Scale', body: 'Increase coverage or spend only after the clinic can see which speciality, source and message are producing useful demand.' },
    ],
    whyUsTag: 'WHY GROWTH ESCALATORS',
    whyUsHeadline: 'Local accountability with performance discipline',
    whyUs: [
      { title: 'Based in Jaipur', body: 'We can work remotely or meet locally when a clinic audit, team workshop or process review benefits from being in person.' },
      { title: 'Marketing + website + automation', body: 'If the constraint is the landing page or follow-up process rather than the ad account, the same team can address it.' },
      { title: 'Speciality pages, not template swaps', body: 'We build different messaging for different patient decisions instead of cloning one healthcare page and changing the doctor type.' },
      { title: 'Conservative healthcare communication', body: 'We prefer accurate, useful claims and clear evidence over aggressive medical promises that create trust and policy problems.' },
    ],
    faqsTag: 'DOCTOR MARKETING QUESTIONS',
    faqsHeadline: 'What Jaipur clinics usually need to know before hiring an agency',
    faqs: [
      { q: 'Should a doctor in Jaipur focus on Google Maps, SEO or Google Ads first?', a: 'It depends on current visibility and treatment demand. High-intent Google Ads can create demand quickly, while Google Maps and organic search compound over time. We normally audit all three before deciding the first priority.' },
      { q: 'Can you market individual specialities rather than the whole clinic?', a: 'Yes. Specialty and treatment intent should usually have its own landing-page and campaign logic. That is especially important for high-consideration services such as orthopaedics, fertility, dermatology and surgery.' },
      { q: 'Do you guarantee Google rankings or patient numbers?', a: 'No. Rankings, ad performance and appointment outcomes depend on competition, budget, reputation, demand, offer quality and clinic operations. We commit to the work, measurement and optimisation process rather than guaranteeing a result we cannot control.' },
      { q: 'Can you help us understand which marketing source produces actual appointments?', a: 'Yes, if the clinic can capture appointment outcomes consistently. We can structure lead-source tracking so the marketing dashboard moves beyond clicks and raw enquiries.' },
      { q: 'Do you work only with Jaipur clinics?', a: 'No. This page is intentionally Jaipur-local for search relevance, while Growth Escalators also works with healthcare businesses outside Jaipur.' },
    ],
    finalCta: { title: 'Find the biggest leak in your patient journey first', subhead: 'Share your clinic, speciality and current marketing. We will tell you which part of the acquisition journey deserves attention before you add more budget.', ctaLabel: 'Book a Free Clinic Audit' },
    videoTestimonials: [],
    relatedResources: {
      tag: 'HEALTHCARE CLUSTER',
      headline: 'Explore the closest healthcare growth pages',
      links: [
        { label: 'Marketing for Doctors & Clinics', href: '/doctors', blurb: 'The national healthcare marketing hub.' },
        { label: 'Patient Acquisition Agency', href: '/patient-acquisition-agency', blurb: 'Patient-funnel and appointment acquisition intent.' },
        { label: 'Personal Branding for Doctors', href: '/personal-branding-for-doctors', blurb: 'Authority building for individual physicians.' },
        { label: 'Dental Clinic Marketing Jaipur', href: '/dental-clinic-marketing-agency-jaipur', blurb: 'Local search and patient acquisition for dental practices.' },
      ],
    },
    leadForm: { recipient: 'Info@growthescalators.com', subjectPrefix: 'New Jaipur Doctor Marketing Lead', headline: 'Tell us about your clinic', subhead: 'Share the speciality, location and growth priority. A strategist will review the patient journey before replying.', tag: 'FREE CLINIC AUDIT' },
  },

  jewelleryJaipur: {
    industryLabel: 'Jaipur Jewellery',
    hero: {
      badge: 'JAIPUR JEWELLERY · SHOWROOM + D2C · META + GOOGLE + CRO',
      headlineLines: ['Marketing Agency for', 'Jewellery Brands in Jaipur'],
      cyclingWords: ['Drive qualified showroom visits.', 'Scale D2C jewellery sales.', 'Build bridal-season demand.', 'Turn trust into conversion.'],
      subhead: 'Growth Escalators works with jewellery businesses that need more than social posting: Jaipur showrooms that want qualified footfall, and D2C jewellery brands that need paid acquisition, ecommerce conversion and stronger product storytelling. One page can serve both models without pretending they are the same funnel.',
      primaryCta: { label: 'Get a Free Jewellery Growth Audit', href: '#lead-form' },
      secondaryCta: { label: 'See D2C Proof ↓', href: '#results' },
      statPills: SHARED_PROOF,
      image: { src: '/industries/jewellery/hero.jpg', alt: 'Premium jewellery display for a Jaipur jewellery brand' },
    },
    painPointsTag: 'TWO DIFFERENT JEWELLERY FUNNELS',
    painPointsHeadline: 'Showroom growth and ecommerce growth need different conversion paths',
    painPoints: [
      { emoji: '💍', title: 'High-ticket trust is missing before the enquiry', body: 'Jewellery buyers inspect craftsmanship, pricing logic, authenticity, reviews, policies and brand credibility before they are willing to message or visit.' },
      { emoji: '📍', title: 'Local searches are not turning into showroom visits', body: 'Weak Maps visibility, incomplete product context and inconsistent reviews can make a strong Jaipur showroom invisible at the moment a buyer is choosing where to visit.' },
      { emoji: '🛒', title: 'D2C traffic reaches a product page that does not close', body: 'Paid acquisition cannot fix unclear product information, weak photography hierarchy, missing trust proof, confusing variants or a poor mobile buying experience.' },
      { emoji: '🎨', title: 'Creative looks premium but does not create buying intent', body: 'Aesthetic content matters, but ads also need use cases, gifting context, bridal intent, price anchors, product detail and reasons to act now.' },
    ],
    aiAdvantage: {
      tag: 'SEO + AI SEARCH READINESS',
      headline: 'Make the brand easier to discover before the buyer knows your name',
      subhead: 'Jewellery discovery increasingly spans Google, Maps, social platforms and AI-assisted research. Clear category, material, occasion, location and trust information helps the brand appear in more of that journey.',
      cards: [
        { emoji: '🔎', title: 'Category & occasion search coverage', body: 'Build useful pages around what people actually look for: bridal, gifting, everyday, material, price tier, style and location intent.' },
        { emoji: '📍', title: 'Jaipur local discovery', body: 'Strengthen showroom entity information, Google Business Profile content and local trust signals without confusing them with national ecommerce intent.' },
        { emoji: '🧾', title: 'Product information that answers buyer questions', body: 'Materials, sizing, care, shipping, returns and authenticity information support conversion and machine-readable understanding.' },
        { emoji: '📈', title: 'Paid traffic tied to conversion pages', body: 'Campaigns are matched to the most relevant collection, product or showroom action instead of sending every visitor to the homepage.' },
      ],
    },
    servicesTag: 'SHOWROOM + D2C CAPABILITY',
    servicesHeadline: 'One jewellery growth partner, two distinct commercial models',
    services: [
      { title: 'Meta Ads for Jewellery', body: 'Creative testing and audience strategy for D2C products, bridal demand, gifting and showroom campaigns where paid social is the right channel.' },
      { title: 'Google Search & Shopping', body: 'Capture high-intent searches and product demand with campaign and feed structures aligned to margin, stock and buyer intent.' },
      { title: 'Google Maps & Local SEO', body: 'For Jaipur showrooms: location pages, GBP optimisation, reviews and local search coverage designed around visits, calls and enquiries.' },
      { title: 'Shopify & Jewellery CRO', body: 'Improve mobile PDP hierarchy, product proof, trust, offers, collections and checkout friction for jewellery sold online.' },
      { title: 'Creative & Product Storytelling', body: 'Build a repeatable creative system across product detail, on-body context, craftsmanship, occasion and customer proof.' },
      { title: 'Attribution & Lead Tracking', body: 'Separate showroom enquiries from ecommerce sales so the business can understand which channels are creating useful demand.' },
    ],
    resultsTag: 'ADJACENT D2C PROOF — LABELLED HONESTLY',
    resultsHeadline: 'We do not pretend a fashion case study is a jewellery case study',
    resultHighlight: {
      label: 'PARAISO · FASHION & LIFESTYLE D2C',
      name: 'D2C acquisition + conversion proof',
      detail: 'Adjacent category proof, not jewellery-specific proof',
      quote: 'Paraiso is used here only to demonstrate Growth Escalators’ existing D2C performance capability. Jewellery-specific case proof should be added when we have a verified jewellery result rather than relabelling another category.',
      metrics: [
        { value: '1.9× → 3.2×', label: 'ROAS' },
        { value: '6×', label: 'Revenue growth in 60 days' },
      ],
    },
    processTag: 'HOW WE PRIORITISE',
    processHeadline: 'Fix the highest-value commercial constraint first',
    process: [
      { step: '01', title: 'Separate the Funnel', body: 'Decide whether the priority is showroom visits, ecommerce sales or both, and give each one its own conversion measurement.' },
      { step: '02', title: 'Audit Demand + Trust', body: 'Review search visibility, Maps, paid media, product pages, creative, reviews and the information buyers need before contacting the brand.' },
      { step: '03', title: 'Improve the Constraint', body: 'Fix the highest-impact issue first — traffic quality, product-page conversion, local visibility, creative or enquiry handling.' },
      { step: '04', title: 'Scale What Holds Margin', body: 'Increase spend and category coverage only where stock, margin and conversion support it.' },
    ],
    whyUsTag: 'WHY GROWTH ESCALATORS',
    whyUsHeadline: 'Jaipur-local capability without limiting the brand to Jaipur',
    whyUs: [
      { title: 'Showroom + ecommerce thinking', body: 'We treat local footfall and online sales as separate funnels instead of forcing both into one reporting number.' },
      { title: 'D2C performance experience', body: 'The team works across acquisition, CRO, Shopify and creative — useful when the ad account is not the real constraint.' },
      { title: 'Local Jaipur presence', body: 'For showroom-led brands, local meetings and on-ground understanding are available when they improve the work.' },
      { title: 'No duplicate national page yet', body: 'We keep this page broad enough to serve Jaipur and D2C intent first, then use Search Console evidence before creating a separate national jewellery page that could cannibalise it.' },
    ],
    faqsTag: 'JEWELLERY MARKETING QUESTIONS',
    faqsHeadline: 'Questions jewellery brands ask before choosing an agency',
    faqs: [
      { q: 'Do you work with both jewellery showrooms and D2C jewellery brands?', a: 'Yes, but the growth system is different. Showrooms usually need Maps, local search, appointment or visit intent and reputation; D2C brands need acquisition, product-page conversion, catalogues and ecommerce measurement.' },
      { q: 'Should we create a separate national D2C jewellery landing page now?', a: 'Not automatically. The existing Jaipur page already covers D2C jewellery intent. We would first strengthen it and use Search Console data to decide whether a separate national page has enough distinct demand to avoid cannibalisation.' },
      { q: 'Can you run both Meta Ads and Google Ads for jewellery?', a: 'Yes, where the product, budget and economics support them. Meta is useful for discovery and creative demand; Google can capture existing search and Shopping intent.' },
      { q: 'Can you help with the Shopify store as well as advertising?', a: 'Yes. Growth Escalators also handles Shopify development and CRO, which matters when paid traffic is reaching a weak product or collection experience.' },
      { q: 'Do you have a verified jewellery-specific case study?', a: 'This page does not claim one today. We show adjacent D2C evidence honestly and will add jewellery-specific proof only when a verified result is available.' },
    ],
    finalCta: { title: 'Find out whether your next rupee belongs in ads, Maps or conversion', subhead: 'Share whether you are showroom-led, ecommerce-led or hybrid. We will audit the funnel around that commercial model instead of giving every jewellery brand the same plan.', ctaLabel: 'Get a Free Jewellery Growth Audit' },
    videoTestimonials: [],
    relatedResources: {
      tag: 'D2C + LOCAL GROWTH',
      headline: 'Related pages for jewellery businesses',
      links: [
        { label: 'D2C Performance Marketing', href: '/d2c', blurb: 'The broader ecommerce growth system.' },
        { label: 'Fashion & Apparel D2C', href: '/d2c/fashion', blurb: 'A mature sub-vertical example of D2C category specialisation.' },
        { label: 'Shopify Development Agency', href: '/shopify-development-agency', blurb: 'Shopify development, CRO and integrations.' },
        { label: 'Performance Marketing Jaipur', href: '/performance-marketing-agency-jaipur', blurb: 'The Jaipur paid-growth hub.' },
      ],
    },
    leadForm: { recipient: 'Info@growthescalators.com', subjectPrefix: 'New Jaipur Jewellery Growth Lead', headline: 'Tell us how your jewellery business sells', subhead: 'Showroom, ecommerce or both — share the current model and the growth constraint you want us to review.', tag: 'FREE JEWELLERY AUDIT' },
  },

  realEstateJaipur: {
    industryLabel: 'Jaipur Real Estate',
    hero: {
      badge: 'JAIPUR REAL ESTATE · DEVELOPERS · PROJECT DEMAND · SITE VISITS',
      headlineLines: ['Real Estate Marketing', 'Agency in Jaipur'],
      cyclingWords: ['Generate qualified project enquiries.', 'Improve site-visit conversion.', 'Launch premium inventory.', 'Track lead quality by project.'],
      subhead: 'Growth Escalators helps Jaipur builders and developers turn digital demand into qualified project enquiries and site visits. We focus on buyer intent, project positioning, landing-page conversion, follow-up and source-level measurement — not the cheapest possible lead.',
      primaryCta: { label: 'Book a Free Project Audit', href: '#lead-form' },
      secondaryCta: { label: 'See Real Estate Proof ↓', href: '#results' },
      statPills: SHARED_PROOF,
      image: { src: '/industries/realestate/4.jpg', alt: 'Premium residential real estate project in Jaipur' },
    },
    painPointsTag: 'WHERE REAL ESTATE FUNNELS LEAK',
    painPointsHeadline: 'Cheap leads are expensive when the sales team cannot turn them into site visits',
    painPoints: [
      { emoji: '🎯', title: 'Campaigns optimise to forms instead of buyer quality', body: 'A low CPL is not useful if most enquiries have the wrong budget, location preference or purchase timeline. Qualification needs to be part of the funnel.' },
      { emoji: '🏗️', title: 'Every project is marketed with the same creative formula', body: 'Luxury apartments, plotted developments and commercial inventory need different hooks, proof, landing pages and buyer journeys.' },
      { emoji: '📲', title: 'Follow-up starts too late', body: 'Real estate demand decays quickly after an enquiry. CRM ownership, WhatsApp acknowledgement and sales-team response need to be designed alongside the campaign.' },
      { emoji: '📊', title: 'Marketing and sales disagree on what worked', body: 'If source, campaign, qualification and site-visit outcomes are not captured consistently, media optimisation becomes a debate rather than a measurement process.' },
    ],
    aiAdvantage: {
      tag: 'SEO + AI SEARCH READINESS',
      headline: 'Make every project easier to understand before the site visit',
      subhead: 'Buyers research location, configuration, price band, amenities, possession, developer trust and comparisons long before they speak to sales. Clear project information supports both search visibility and conversion.',
      cards: [
        { emoji: '🗺️', title: 'Project + micro-market search coverage', body: 'Build pages around the project and the location intent buyers use instead of relying on a brochure PDF and a generic developer homepage.' },
        { emoji: '🏠', title: 'Decision-ready landing pages', body: 'Configuration, location, amenities, project status, FAQs and enquiry actions are structured around buyer questions.' },
        { emoji: '🧠', title: 'Qualification before sales effort', body: 'Capture the few questions that help distinguish serious project fit without adding so much friction that good buyers abandon the form.' },
        { emoji: '🔁', title: 'Search-to-site-visit measurement', body: 'Where CRM data is available, connect campaign sources to qualified leads and site-visit outcomes so optimisation follows commercial value.' },
      ],
    },
    servicesTag: 'PROJECT DEMAND SYSTEM',
    servicesHeadline: 'From project positioning to qualified site visits',
    services: [
      { title: 'Meta Lead Generation', body: 'Creative, audience, lead forms and landing-page campaigns designed around project fit rather than raw enquiry volume.' },
      { title: 'Google Search Ads', body: 'Capture buyers searching for project, location, property type and high-intent real estate terms.' },
      { title: 'Project Landing Pages', body: 'Mobile-first project pages that answer buyer questions and make it easy to request details, schedule a visit or continue on WhatsApp.' },
      { title: 'CRM & WhatsApp Follow-up', body: 'Structure source capture, acknowledgement and lead routing so the sales team can respond quickly and consistently.' },
      { title: 'Real Estate Creative', body: 'Project hooks, location stories, walkthroughs, amenity proof and retargeting creative matched to the stage of the buyer journey.' },
      { title: 'Lead Quality Reporting', body: 'Move reporting from forms and CPL toward qualified leads, site visits and the reasons leads are being rejected.' },
    ],
    resultsTag: 'VERIFIED REAL ESTATE PROOF',
    resultsHeadline: 'A real Jaipur developer result already in our evidence set',
    resultHighlight: {
      label: 'LUXURY RESIDENTIAL PROJECT · JAIPUR',
      name: 'Arjun Singhania',
      detail: 'Real Estate Developer, Jaipur',
      quote: 'We launched a luxury residential project and had no digital presence. Growth Escalators built our entire funnel — Meta ads, landing page, WhatsApp follow-up. Within 60 days we had 3x more qualified site visits than our previous project.',
      metrics: [
        { value: '3×', label: 'Qualified site visits vs previous project' },
        { value: '60 days', label: 'Reported period' },
      ],
    },
    processTag: 'OUR SIX-SIGMA-INSPIRED PROJECT LOOP',
    processHeadline: 'Optimise the constraint between enquiry and site visit',
    process: [
      { step: '01', title: 'Measure', body: 'Audit project positioning, lead sources, landing pages, response time, qualification and site-visit conversion.' },
      { step: '02', title: 'Diagnose', body: 'Identify whether the primary leak is demand, audience fit, page conversion, qualification, response or sales follow-up.' },
      { step: '03', title: 'Improve', body: 'Fix the highest-impact constraint with targeted campaign, page, creative or process changes.' },
      { step: '04', title: 'Scale', body: 'Increase media and project coverage only when the sales team can see which demand sources are producing useful buyer conversations.' },
    ],
    whyUsTag: 'WHY GROWTH ESCALATORS',
    whyUsHeadline: 'Jaipur presence with a performance funnel mindset',
    whyUs: [
      { title: 'Local market context', body: 'The team is based in Jaipur and can work directly with project and sales teams when local coordination improves launch speed.' },
      { title: 'Marketing + landing pages + tracking', body: 'The campaign, project page and measurement layer can be handled together instead of split across vendors.' },
      { title: 'Lead quality over vanity CPL', body: 'We prefer a more expensive lead that fits the project over a cheap form submission the sales team will reject.' },
      { title: 'Built to expand into project-launch intent', body: 'The local page handles Jaipur agency-hire intent, while a separate project-launch page can target the higher-value launch problem without cannibalising the local page.' },
    ],
    faqsTag: 'DEVELOPER QUESTIONS',
    faqsHeadline: 'What Jaipur builders should ask before hiring a real estate marketing agency',
    faqs: [
      { q: 'How should a Jaipur real estate developer judge marketing performance?', a: 'CPL is only an early indicator. A stronger view includes lead fit, contact rate, qualified conversations, site visits and the reasons sales is rejecting enquiries.' },
      { q: 'Should we use Meta Ads or Google Ads for a real estate project?', a: 'Often both play different roles. Meta can create and retarget demand; Google captures buyers already searching for projects, locations and property types. The mix depends on the project and budget.' },
      { q: 'Can you work with our existing CRM and sales team?', a: 'Yes. We prefer to align source capture, qualification and feedback with the sales workflow so media optimisation can use better outcome data.' },
      { q: 'Do you guarantee bookings or sales?', a: 'No. Property sales depend on price, inventory, location, market demand, financing, sales execution and many factors outside an agency’s control. We optimise the measurable acquisition and conversion system.' },
      { q: 'Do you also handle project launches?', a: 'Yes. We are creating a dedicated project-launch marketing page for launch-specific intent, while this page remains focused on hiring a real estate marketing agency in Jaipur.' },
    ],
    finalCta: { title: 'Audit the path from ad click to site visit before increasing spend', subhead: 'Share the project, price band, location and current lead flow. We will identify the part of the funnel most likely to be holding qualified visits back.', ctaLabel: 'Book a Free Project Audit' },
    videoTestimonials: [],
    relatedResources: {
      tag: 'REAL ESTATE CLUSTER',
      headline: 'Related real estate growth pages',
      links: [
        { label: 'Real Estate Marketing', href: '/real-estate', blurb: 'The national real estate growth hub.' },
        { label: 'Performance Marketing Jaipur', href: '/performance-marketing-agency-jaipur', blurb: 'Local paid media and acquisition.' },
        { label: 'Website Development Jaipur', href: '/website-development-company-jaipur', blurb: 'Project and developer website development.' },
      ],
    },
    leadForm: { recipient: 'Info@growthescalators.com', subjectPrefix: 'New Jaipur Real Estate Marketing Lead', headline: 'Tell us about the project', subhead: 'Share location, property type, price band and the lead-quality problem you want us to review.', tag: 'FREE PROJECT AUDIT' },
  },
}

export default function PriorityLocalLanding({ pageKey }: { pageKey: PriorityLocalKey }) {
  return <IndustryLandingPage content={PRIORITY_LOCAL_PAGES[pageKey]} />
}
